name: amateure-eyes-test
on: 
  push:
    branches:[master]
    pull_request:
      branches:[elham]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12.00
          cache: "npm"
      - run: npm install
      - run: npm test